---
---

# Print one of John's amazing lyrics.
quotes = [
    "I would do anything for you",
    "starving to death for the low-hanging fruit",
    "I will carry you home in my teeth",
    "there's power in the name",
    "so many so-called friends working for the government",
    "so this is what the volume knob's for",
    "I saw the future in a dream last night",
    "we belong dead",
    "I got joy, joy, joy in my soul tonight",
    "I shot him in the face",
    "the only thing I know is that I love you",
    "hail satan",
    "we grow nameless as we feel the blood race",
    "wind up on your own floor choking on blood",
    "if I never get there at all, would you leave the seat empty?",
    "from the aspirins to the cross-tops to the elavils",
    "mission to no place",
    "and then where is there left for poor sinners to go",
    "jettison all dead weight",
    "I am evil forest",
    "I hear you talking &mdash; shut up",
    "stare down demons and come back breathing",
    "prayers to summon the destroying angel",
    "goodbye young swedish women",
    "dream all night of freedom, never wake up free",
    "you got no manners at all",
    "god bless all petty thieves",
    "you'll tell me about all your thoughts right this minute",
    "go down to the netherworld",
    "lord, send me a mechanic",
    "sounds of a distant storm",
    "no brothers left",
    "every moment points towards the aftermath",
    "dead languages on our tongues",
    "old things made new",
    "ugly things in the darkness",
    "your drunken kisses as light as the air",
    "the dead will walk again",
    "stay the hell out of my way",
    "sweating out the poison",
    "sing, sing, sing for the dying of the day",
    "I am the killer dressed in pilgrim's clothing",
    "one for me, one for your doubts, and one for god",
    "the flesh was very, very strong",
    "I've gone feral, and I don't speak the language anymore",
    "I mouth my silent curses at you",
    "you slipped free",
    "we were rising from the grave",
    "figured I'd just play it like it lays",
    "full moon, deep grass, cold water",
    "I saw you in the blazing light",
    "and then the cold sorrow gripped me by the throat",
    "I'm gonna miss you when you're gone",
    "the last of the repercussions",
    "empty promises",
    "stepped away from the killing floor",
    "I will know who you are yet",
    "we were real hungry and half dead",
    "I know you're changing",
    "trying to cool down",
    "I carved out little figurines of thieves",
    "someday I am going to walk out of here free",
    "when you came in, I could breathe again",
    "my enemies hide in the dark like roaches",
    "nothing anyone could do",
    "you could have popped the tension with a safety pin",
    "all-embracing wreckage, sunburned and snowblind",
    "put me in a beat-up el camino, just let me go, let me go",
    "the crows, crows, crows, rose, rose rose from the grave",
    "we're gonna sail through the night sky like a pair of bottle rockets",
    "let me serve you with my body",
    "and the chicago cubs will beat every team in the league",
    "I am digging graves",
    "here's your lonesome surprise",
    "where did the monkey come from",
    "the flames rose hundreds of feet into the air",
    "boil, boil",
    "someday, someday, mount fuji's gonna blow",
    "tried my new self on for size",
    "watched the hypodermic needles coming in with the tide",
    "hang on to your dreams until there's nothing left of them",
    "these roses are the pleasures of the flesh",
    "dream all night of freedom, never wake up free",
    "we are sleek and beautiful, we are cursed",
    "I hope they incinerate everybody in it",
    "empty hearts on fire",
    "we're all here chewing our tongues off",
    "there is someone waiting out there with a mouthful of surprises",
    "walking gingerly across the bruised earth",
    "out in the desert we'll live carefree",
    "shoving our heads straight into the guts of the stove",
    "force it down like it was medicine",
    "toxic clear down to the bedrock",
    "when the last days come we shall see visions",
    "I come from Chino so all your threats are empty",
    "no grave is ever gonna hold me",
    "I'm going to be restored",
    "day gives way to day gives way to day gives way to day",
    "what happens on the day that I forget",
    "good news like a rare blood disorder",
    "that's not the sun up in the sky, it's a human heart",
    "the ice cream was blacker than the devil's heart",
    "you smile at me in total defiance of all decency",
    "I grab hold of your hip and I pull you in",
    "heads are gonna roll",
    "blue water, white sky",
    "I have two big hands and a heart pumping blood",
    "into the fire you go",
    "there are no windows or doors and the walls are on fire",
    "you rushed for an average of eight and a third yards per carry",
    "he was broken pretty bad, so we gave him what we had",
    "we were the one thing in the galaxy god didn't have his eyes on",
    "I got a cracked engine block, both of us do",
    "trying to squeeze tears out of mute stones",
    "the roots reach down to where the bad people go",
    "you find shelter somewhere in me",
    "felt such love for you I thought my heart was gonna pop",
    "after three nights in jail",
    "a small prayer for the poor and the naked and the hungry",
    "chevy impalas in their front yards up on blocks",
    "one long season of waiting",
    "never learned the value of a penny",
    "waiting for Jesus to come along and save us",
    "st. joseph's baby aspirin",
    "I write down good reasons to freeze to death",
    "I am gonna make it through this year if it kills me",
    "things your body wasn't meant to",
    "looking at the void and seldom blinking",
    "our mother has been absent ever since we founded Rome",
    "hold on for dear life",
    "I am young and I am good",
    "shore up the crucifixes",
    "I'll be down among the jumpers",
    "the things you do for love are gonna come back to you one by one",
    "shortly after your first heart attack",
    "tearing up the charts",
    "scoop up the guts and brains",
    "here comes a new genuine disaster",
    "that's a damnable lie",
    "I got special shoes on",
    "and the easter bunny's coming and god knows I'd hate for you to miss it",
    "the air was thick with alcohol",
    "you heard the moon roar",
    "I am glad I am alive",
    "your fingers dripping kerosene",
    "I am the fire that burns without wood",
    "on the morning you went away",
    "hoping I'd run into you",
    "black bandages on my eyes",
    "all of you, all of you, rage, rage, rage",
    "god is present in the sweeping gesture",
    "the unmistakable scent of brilliantine",
    "I saw the sign",
    "let me die, let me die surrounded by machines",
    "body after body alone",
    "oh, solitude, friend of the friendless",
    "I'm not all right",
    "like a man whose veins have frozen overnight",
    "sustenance, blessed sustenance",
    "kalpadruma trees melting in the heat",
    "breakdancing on the sidewalk",
    "this church is rotten from the top down",
    "said the prayer you taught me to keep myself alive",
    "don't bring me back alive",
    "I love you because you gave me sausage and cheese when I was hungry",
    "the door will surely kill you",
    "you opened up your eyes and the Lord came out",
    "it was every good thing I'd expected it to be",
    "when the priest came to call, I sent him on his way",
    "doctor says that I've got 30 days left at most",
    "I ate so much carrion that I could not move",
    "I knew that I would be all right",
    "write down good reasons to freeze to death",
    "take your foot off of the brake",
    "it's gonna take you people years to recover from all of the damage",
    "hold on for dear life",
    "I am the last of a lost civilization",
    "shore up the crucifixes",
    "when the birds come home in spring, we will fill them full of buckshot",
    "we shall see each other face to face",
    "she told me how you died at last, at last",
    "ready to die",
    "artlessly shoplifting random things",
    "symmetrical and pure as a pagoda",
    "everything I love I will devour",
    "I hope they've got plenty of money where you're going",
    "but I hold you anyway",
    "thought I saw a mouse kicking in your beak, it was only a skeleton",
    "breath rising and falling",
    "I am losing control of the language again",
    "I want you more than I want anything",
    "I thought I'd figured out the world and its circular way",
    "I don't speak the language down here",
    "on the day that I forget you I hope my heart explodes",
    "we can taste fresh blood in our mouths again",
    "listening for the old sound",
    "you were knocking",
    "I should not be allowed to touch anything",
    "and then they put me in jail 'til you were 23",
    "just the old love, asking for more again",
    "black and white footage of the young cassius clay",
    "the unfathomable heat",
    "you punish me with pity",
    "and the sun sets on the good and the evil",
    "you were warm and that's all I remember",
    "now I have everything I need",
    "I'm only getting stronger, you may have noticed",
    "you ask me to hold you, that's the devil's work",
    "bad luck cruised by on his ten-speed bike",
    "you sent me a package marked 'live animals inside'",
    "pocketful of medicine to abuse myself with",
    "would you please just go away",
    "see the flames rise to the sky",
    "god will give him blood to drink",
    "when I saw you against the soda machine",
    "make for the other world",
    "let me break their jaws",
    "well, you know you're dying, and I know you're dying too",
    "your laughter tore through the new jersey night",
    "as the sun went away it was sending out signals",
    "red, red, red everywhere",
    "I put a bullet through its cold, dead brain",
    "your love came screaming through me",
    "you must try to lead a good life",
    "as we crossed over the throgs neck bridge",
    "I had a present for you hidden somewhere",
    "these days, these days we drink a lot of snake oil",
    "it was hot but not too hot",
    "they used to paint their bodies blue",
    "tell me why",
    "I was in between times",
    "we gathered up our worldly goods",
    "you cry when you get drunk",
    "whose bones are these",
    "I am heading your way all the time",
    "if you leave, you're gonna get athlete's foot",
    "don't take the dogs away",
    "every hour every minute every second of the day",
    "I've got a radio",
    "the soil is soaked through with old blood and with relatives",
    "god damn these vampires",
    "one clear shot or else he gets away",
    "crash in from deep space",
    "the faithless few",
    "I feel guilty but I can't feel ashamed",
    "and then the grass grows up to cover up the firepit and the forge",
    "the things that hurt you most",
    "never let them see you're weak",
    "lay down your heavy load",
    "anyone here mentions hotel california dies before the first line clears his lips",
    "never get away, never get away, I am never ever gonna get away from this place",
    "the labyrinth is lightless",
    "come and rattle your chain",
    "the dust of Jedi bones piled high like parsnips on his plate",
    "this song is for the rats",
    "black out for local TV",
    "now your ashes are scattered on the wind",
    "all soaked in blood like a newborn babe",
    "through the noise I hear you call for help",
    "I can see the future, it's a real dark place",
    "I don't want to die in here",
    "the pure at heart go putrid",
    "all gone",
    "crude and graceless",
    "never die, never die",
    "get new ones in completely garish hues",
    "one whole life recorded in disappearing ink",
    "I'm still here, but all is lost",
    "forge my armor in the old fire",
    "stand there and watch them drown",
    "hunt us like dogs",
    "perfect howl of emptiness",
    "just stay alive",
    "in the nameless dark",
    "waving torches",
    "I will get lonely",
    "ghosts and clouds and nameless things",
    "always wake up alone",
    "like a drifter to an on-ramp",
    "just 'cause you hate it when I let things go to waste",
    "when the villagers come to my door",
    "raise children from stones",
    "leave me alone 'til I learn how to spin straw into gold",
    "toxicity near saturation levels",
    "the ghost on your doorstep has to eat same as you",
    "he clutches at his stomach and howls at the pain",
    "when we had run out of cocaine",
    "feel the fear in my chest all day",
    "the blood that's been spilling from his eyes",
    "smoldering bodies at my feet",
    "there won't be any people left to cry for",
    "thank god for small favors in high doses",
    "desperate pleas and vicious lies",
    "you and me are gonna get drunk tonight",
    "your eyes burned through me",
    "mulch what's dying on the vine",
    "leaving you behind in the sand",
    "the seal is the sworn enemy of man",
    "the table's hot and so am I",
    "a part of raccoons heading to the gutter",
    "there are no words at all",
    "you showed me a thing or two about power in its purest form",
    "gas fumes rising from the blacktop",
    "perched above the symbols she painted on the garden wall",
    "don't call me at 3 AM from your friend's apartment",
    "the incredibly, impossibly dry air",
    "new rumors of war",
    "I got all my hopes hung on your one gorgeous promise",
    "like a flower caught in the overgrowth",
    "strange black birds",
    "I did not come here to suffer",
    "the fourth new tree is my enemy",
    "where did our love go",
    "made a bitter man of me",
    "it made me wish I was dead",
    "all the chances that we burned",
    "everyone you know is gone",
    "looked out at the awful sky",
    "I let her right on in",
    "I got lost when my lucky stars crossed",
    "the burning and the electricity",
    "our love is like jesus but worse",
    "this is the worst place",
    "bad things never die",
]

numQuote = Math.floor(Math.random() * quotes.length)
document.write '<p class="epigraph">' + quotes[numQuote] + '</p>'
